### ISSUE TITLE
Installation failed with "No registered operation handler"

### ISSUE THREAD

**Issue by wbiker** [lizmat/P5getpriority#1]
Tests fail with "No registered operation handler for 'getppid'".

OS: arch
Perl6: This is Rakudo Star version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.
Command Line:
zef install P5getpriority

**Comment by lizmat** [comment]
Thanks for the report!

It appears that nqp::getppid got added pretty recently.  Short-term solutiion: get a more recent Rakudo.  Longer term: will look at this tomorrow to fix for older Rakudo versions.

**Comment by lizmat** [comment]
Turns out this was easier to fix than I thought: a new version is on its way to CPAN!  Could you please confirm this fixes it for you?

**Comment by wbiker** [comment]
Cool, you are fast ^^.
Thanks for the work. Will test the new version when it hits CPAN. At the moment of writing it is still 0.0.4

**Comment by lizmat** [comment]
I think a new index for modules.perl6.org is generated every 3 hours or so.

**Comment by wbiker** [comment]
Great. Works as expected!
Thanks for your work, Liz!
